# Generated by Django 6.0.5 on 2026-06-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('tanggal_terbit', models.DateField()),
                ('total_stok', models.PositiveIntegerField(default=1, verbose_name='Total Buku Fisik')),
                ('buku_display', models.PositiveIntegerField(default=1, verbose_name='Jumlah Buku Display')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
