# Generated by Django 6.0.5 on 2026-06-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('nim_peminjam', models.CharField(max_length=20)),
                ('telp_peminjam', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=255)),
                ('kode_buku', models.CharField(max_length=255)),
                ('tanggal_wajib_kembali', models.DateField()),
                ('status', models.CharField(default='Dipinjam', max_length=20)),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='peminjaman.peminjaman')),
            ],
        ),
    ]
